from dataclasses import dataclass
import torch
import numpy as np
import torch.nn.functional as F


torch.set_default_dtype(torch.float64)

@dataclass
class GaussianPulseSequence:
    """
    Generates a sequence of Gaussian pulses with random centers and random time delays if time_delay not None. 
    """

    n_pulse: int = 50
    time_delay: int = 5
    init_pulse: torch.Tensor = None
    output_pulses: torch.Tensor = None


    def __post_init__(self):
        self._generate_sequence()

    def _generate_sequence(self) -> None:

        if self.time_delay is None:
            self.time_delay = np.random.randint(3, 5) # fix time delay

        pulses = []
        shifted_pulse = np.roll(self.init_pulse, self.time_delay)
        pulses.append(shifted_pulse / shifted_pulse.max())

        for _ in range(self.n_pulse-1):
            shifted_pulse = np.roll(shifted_pulse, self.time_delay)
            pulses.append(shifted_pulse / shifted_pulse.max())

        self.output_pulses = torch.tensor(np.array(pulses)).squeeze(-1).T


@dataclass
class RNNSequence:
    """
    Generates a sequence of gaussian pulses with an RNN with W_hh with subdiagonal entries = 1
    """

    n_neuron: int = 50
    init_pulse: torch.Tensor = None
    chain_length: int = None
    output_pulses: torch.Tensor = None
    activation_function: str = 'linear'
    chain_idx: int = None
    W_hh: torch.Tensor = None
    W_ih: torch.Tensor = None
    T: torch.Tensor = None
    Q: torch.Tensor = None


    def __post_init__(self):
        """Initializes RNN matrices and generates output sequence."""
        self._initialize_T()
        self._initialize_W_hh()
        self._initialize_W_ih()
        self._generate_sequence()


    def _initialize_T(self) -> None:
        if self.T is not None:
            return

        #draw for diag negative eigenvalues from a uniform distribution, negative sign for subdiagonal entries
        diag_entries = np.random.uniform(low=-.9,high=-.6, size=self.n_neuron)
        subdiag_entries = np.zeros(self.n_neuron - 1, dtype=float)

        if self.chain_length is None:
            self.chain_length = self.n_neuron
            rand_idx = 1
        else:
            rand_idx = np.random.randint(1,np.round(self.n_neuron/2))
        
        self.chain_idx = rand_idx

        subdiag_entries[rand_idx-1:rand_idx-1+self.chain_length] = -1*diag_entries[rand_idx:rand_idx+self.chain_length-1]
        subdiag_entries[0:self.n_neuron-1] = -1*diag_entries[1:]

        diag_mat = np.diag(diag_entries)
        subdiag_mat = np.diag(subdiag_entries,k=-1)
        self.T = torch.tensor(diag_mat + subdiag_mat) # default T is a Schur form with very weak self feedback connections

    def _initialize_W_hh(self) -> None:
        if self.W_hh is not None:
            return
        
        self.Q = torch.tensor(np.identity(self.n_neuron))
        self.W_hh = self.Q.T @ self.T @ self.Q # is equal to T with identity matrix as Q

    def _initialize_W_ih(self) -> None:
        if self.W_ih is not None:
            return
        
        t = torch.tensor([0], dtype=torch.float64)
        self.W_ih = t.repeat(self.n_neuron,1).squeeze(-1)
        W_ih = self.W_ih.clone()
        W_ih[self.chain_idx-1] = 1.

    def _generate_sequence(self) -> None:
        hidden_units = []
        t = torch.tensor([0], dtype=torch.float64)
        original_h = t.repeat(self.n_neuron,1).squeeze(-1)
        h_0 = original_h.clone()
        
        if self.activation_function == 'linear':
            activation_function = torch.nn.Identity()
        else:
            activation_function = F.tanh

        for i in range(len(self.init_pulse)):

            h_t = h_0 + activation_function((self.W_hh @ h_0 + self.W_ih * self.init_pulse[i]))
            hidden_units.append(h_t.permute(*torch.arange(h_t.ndim - 1, -1, -1)))
            h_0 = h_t

        self.output_pulses = torch.tensor(np.array(hidden_units)).squeeze(-1)

        


class GaussianPulseDataset(torch.utils.data.Dataset):
    """
    Generates a dataset of sequences of Gaussian pulses. 
    Sequences can be generated by either a simple Gaussian pulse sequence with random time delays or by an RNN.
    """

    def __init__(self, n_pulse=18, n_samples = 100, seq_length=200, sequence_type='gaussian', time_delay=None, chain_length=None, activation_function='linear'):
        self.n_pulse = n_pulse
        self.n_samples = n_samples
        self.seq_length = seq_length
        self.time_delay = time_delay
        self.chain_length = chain_length
        self.sequence_type = sequence_type
        self.activation_function = activation_function
        self.sequence = None
        self.init_pulse: torch.Tensor = None


    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        
        center = np.random.randint(-int(self.seq_length/3),-int(self.seq_length/5))
        pulse_width = np.random.uniform(1,3)
        amplitude = np.random.uniform(1,8.)
        self.init_pulse = torch.tensor(np.roll(
            torch.signal.windows.gaussian(self.seq_length, std=pulse_width), center)).unsqueeze(-1)*amplitude

        if self.sequence_type == 'rnn':
            self.sequence = RNNSequence(n_neuron=self.n_pulse, init_pulse=self.init_pulse, chain_length=self.chain_length, activation_function=self.activation_function)
        else:
            self.sequence = GaussianPulseSequence(
                n_pulse=self.n_pulse, time_delay=self.time_delay, init_pulse=self.init_pulse)

        return self.init_pulse, self.sequence.output_pulses